# Generated by Django 2.2.15 on 2020-08-21 18:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200809_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='videos',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videos',
            name='text',
            field=models.TextField(default=django.utils.timezone.now, max_length=1000),
        ),
    ]
