# Generated by Django 2.2.15 on 2020-08-21 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200821_1152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'image', 'verbose_name_plural': 'images'},
        ),
    ]
