# Generated by Django 2.2.15 on 2020-08-24 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_hey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hey',
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'image', 'verbose_name_plural': 'images'},
        ),
        migrations.RemoveField(
            model_name='images',
            name='images',
        ),
        migrations.AddField(
            model_name='document',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='document',
            name='images',
            field=models.FileField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='document',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='text',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='image',
            field=models.FileField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='images',
            name='text',
            field=models.TextField(default=django.utils.timezone.now, max_length=1000, null=True),
        ),
    ]
