# Generated by Django 2.2.15 on 2020-08-24 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200824_0725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={},
        ),
        migrations.RemoveField(
            model_name='document',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='document',
            name='images',
        ),
        migrations.RemoveField(
            model_name='document',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='document',
            name='text',
        ),
        migrations.RemoveField(
            model_name='document',
            name='title',
        ),
    ]
