# Generated by Django 2.2.15 on 2020-08-24 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200824_0900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'video', 'verbose_name_plural': 'videos'},
        ),
    ]
