# Generated by Django 2.2.15 on 2020-08-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='images',
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.FileField(null=True, upload_to='image/'),
        ),
    ]
