# Generated by Django 2.2.15 on 2020-08-24 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20200824_1141'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='Images',
        ),
    ]
